version: '3'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  postgres:
    image: 'postgres:latest'
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'

  brokerage-api:
    image: brokerage-api:latest
    volumes:
      - ~/.m2:/root/.m2
    ports:
      - '8080:8080'
    environment:
      - POSTGRESQL_URL=jdbc:postgresql://postgres:5432/postgres
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_URL=kafka:9092
      - ACTIVE_PROFILE=dev
    depends_on:
      - kafka
      - postgres
      - redis
